# Generated by Django 2.2.5 on 2022-02-20 22:00

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sensor_type', models.CharField(choices=[('pressure', 'Pressure'), ('temperature', 'Temperature')], default=('temperature', 'pressure'), max_length=80)),
                ('sensor_value', models.DecimalField(decimal_places=1, max_digits=5)),
                ('sensor_reading_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
