# Generated by Django 2.2.5 on 2022-02-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='sensor_type',
            field=models.CharField(choices=[('pressure', 'Pressure'), ('temperature', 'Temperature')], default='temperature', max_length=80),
        ),
    ]
